
---LISTA 2

SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM SUPPLIER
--LETRA A
SELECT NMCUSTOMER,IDFONE FROM CUSTOMER WHERE IDFONE  LIKE '4%';

--LETRA B
SELECT NMCUSTOMER,IDFONE FROM CUSTOMER WHERE IDFONE=NULL;

--LETRA C
SELECT NMSUPPLIER,IDFONE FROM SUPPLIER WHERE IDFONE  NOT LIKE '(%';

--LETRA D
SELECT NMPRODUCT,QTSTOCK, VLPRICE=VLPRICE-(VLPRICE*10)/100  FROM PRODUCT WHERE QTSTOCK>2000 ;
--APENAS PRA CONFERIR
SELECT *FROM PRODUCT

--LETRA E
SELECT NMPRODUCT,VLPRICE  FROM PRODUCT WHERE VLPRICE BETWEEN '10' AND '20' ;
--APENAS PRA CONFERIR
SELECT *FROM PRODUCT

--LETRA F 
SELECT NMPRODUCT,VLPRICE, QTSTOCK*VLPRICE AS PTOTAL FROM PRODUCT WHERE VLPRICE > 50 ;
--APENAS PRA CONFERIR
SELECT *FROM PRODUCT

--LETRA G
SELECT NMPRODUCT,S.NMSUPPLIER,S.IDFONE 
FROM PRODUCT 
INNER JOIN SUPPLIER AS S ON PRODUCT.CDSUPPLIER= S.CDSUPPLIER
WHERE PRODUCT.VLPRICE>20 AND PRODUCT.QTSTOCK>1500;
--APENAS PRA CONFERIR 
SELECT *FROM PRODUCT
SELECT *FROM SUPPLIER

--LETRA H
SELECT C.NMCUSTOMER,DTREQUEST,VLTOTAL
FROM REQUEST AS R 
INNER JOIN CUSTOMER AS C ON R.CDCUSTOMER= C.CDCUSTOMER
WHERE R.DTREQUEST BETWEEN '2003/06/01' AND '2003/07/31'
 --APENAS PRA CONFERIR 
SELECT *FROM CUSTOMER
SELECT *FROM REQUEST

--LETRA I
SELECT 
C.NMCUSTOMER, P.NMPRODUCT , R.DTREQUEST , PR.QTAMOUNT , PR.VLUNITARY , PR.VLUNITARY*PR.QTAMOUNT AS VALORTOTAL
FROM REQUEST AS R
INNER JOIN CUSTOMER AS C ON R.CDCUSTOMER= C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON R.CDREQUEST=PR.CDREQUEST
INNER JOIN PRODUCT AS P ON PR.CDPRODUCT= P.CDPRODUCT
WHERE PR.QTAMOUNT>500
--APENAS PRA CONFERIR 
SELECT *FROM REQUEST
SELECT *FROM PRODUCT
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCTREQUEST