

--LISTA 3
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM SUPPLIER
SELECT *FROM PRODUCT

--LETRA A
SELECT * FROM
(SELECT 
P.NMPRODUCT,
S.NMSUPPLIER,
P.VLPRICE,
P.VLPRICE-(P.VLPRICE*10)/100 AS DES10,
P.VLPRICE-(P.VLPRICE*20)/100 AS DES20,
P.VLPRICE-(P.VLPRICE*30)/100 AS DES30 
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER)AS PRODUTO
WHERE PRODUTO.DES10>15 ORDER BY PRODUTO.VLPRICE 
--APENAS PRA CONFERIR
SELECT *FROM SUPPLIER
SELECT *FROM PRODUCT

--LETRA B
SELECT * FROM
(SELECT 
P.NMPRODUCT,
S.NMSUPPLIER,
P.VLPRICE,
p.VLPRICE*p.QTSTOCK AS TOTALSTOCK,
p.VLPRICE*(p.QTSTOCK*2) AS DOBROSTOCK
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER) AS PRODUTO
WHERE PRODUTO.TOTALSTOCK>12000 ORDER BY PRODUTO.NMSUPPLIER, PRODUTO.NMPRODUCT
--APENAS PRA CONFERIR
SELECT *FROM PRODUCT

--LETRA C
SELECT * FROM CUSTOMER WHERE IDFONE IS NOT NULL AND NMCUSTOMER LIKE 'J%';

--LETRA D
SELECT*FROM
(SELECT 
P.NMPRODUCT,
P.VLPRICE,
S.NMSUPPLIER
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER) AS PRODUTO
WHERE PRODUTO.NMSUPPLIER LIKE '%ica%' ORDER BY PRODUTO.NMSUPPLIER,PRODUTO.VLPRICE


-- LETRA E
SELECT 
S.NMSUPPLIER,
S.IDFONE,
P.NMPRODUCT,
P.VLPRICE,
P.QTSTOCK*P.VLPRICE
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.NMPRODUCT LIKE 'S%' AND P.VLPRICE>50
ORDER BY S.NMSUPPLIER,P.VLPRICE

--LETRA F
SELECT
C.NMCUSTOMER,
P.NMPRODUCT,
R.DTREQUEST,
R.DTDELIVER,
PR.QTAMOUNT,
PR.VLUNITARY,
PR.VLUNITARY*PR.QTAMOUNT AS TOTAL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON C.CDCUSTOMER=R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
WHERE PR.QTAMOUNT<600 
AND R.DTREQUEST BETWEEN '2003/08/01' AND '2003/08/31' 
AND P.NMPRODUCT LIKE 'M%'
--APENAS PRA CONFERIR 
SELECT *FROM CUSTOMER
SELECT *FROM REQUEST
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST

--LETRA G
SELECT 
C.NMCUSTOMER,
P.NMPRODUCT,
S.NMSUPPLIER,
R.DTREQUEST,
R.VLTOTAL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON C.CDCUSTOMER=R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
INNER JOIN SUPPLIER AS S ON S.CDSUPPLIER=P.CDSUPPLIER
WHERE S.IDFONE LIKE '(011)%' AND R.VLTOTAL>20 