---LISTA 4

---------------------------------------
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM SUPPLIER
---------------------------------------
--LETRA A
SELECT DISTINCT P.NMPRODUCT  
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P ON PR.CDPRODUCT=P.CDPRODUCT
GROUP BY P.NMPRODUCT

--LETRA B
SELECT  P.NMPRODUCT, COUNT( PR.CDREQUEST) AS VEZES, SUM(QTAMOUNT) AS QTPEDIDA
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P ON PR.CDPRODUCT=P.CDPRODUCT
GROUP BY P.NMPRODUCT

-------------------------------------------------------------------------------------------------
--LETRA C
SELECT
 FORNCEDOR.NMSUPPLIER,
 FORNCEDOR.STOCKTOTAL,
 FORNCEDOR.AVGVLPREICE,
 FORNCEDOR.TLPRODUCT
FROM
(SELECT 	
	S.NMSUPPLIER,
	SUM (P.QTSTOCK) AS STOCKTOTAL,
	AVG (P.VLPRICE) AS AVGVLPREICE,
	COUNT (P.CDSUPPLIER) AS TLPRODUCT
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER GROUP BY S.NMSUPPLIER)AS FORNCEDOR
--TEST DO SELECT
SELECT 	
	S.NMSUPPLIER,
	SUM (P.QTSTOCK) AS STOCKTOTAL,
	AVG (P.VLPRICE) AS AVGVLPREICE,
	COUNT (P.CDSUPPLIER) AS TLPRODUCT 
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER GROUP BY S.NMSUPPLIER,P.CDSUPPLIER
--APENAS PRA TESTAR
 SELECT *FROM SUPPLIER
 SELECT *FROM PRODUCT

 ---------------------------------------------------------------------------------------------
--LETRA D
SELECT CLIENTE.NMCUSTOMER,CLIENTE.IDFONE,CLIENTE.VALORMX,CLIENTE.VALORMN,CLIENTE.TOTAL,CLIENTE.AGVTL FROM
(
	SELECT 
		C.NMCUSTOMER,
		C.IDFONE,
		MAX (R.VLTOTAL) AS VALORMX,
		MIN (R.VLTOTAL) AS VALORMN,
		SUM (R.VLTOTAL) AS TOTAL,
		AVG (R.VLTOTAL) AS AGVTL
	FROM CUSTOMER AS C 
	INNER JOIN REQUEST AS R ON C.CDCUSTOMER=R.CDCUSTOMER
	GROUP BY C.NMCUSTOMER,C.IDFONE) AS CLIENTE
ORDER BY CLIENTE.VALORMX DESC;
--CONFERENCIA 
SELECT *FROM REQUEST
SELECT *FROM PRODUCTREQUEST
SELECT *FROM CUSTOMER

--LETRA E
SELECT * FROM (SELECT 
	R.DTREQUEST, 
	C.NMCUSTOMER,
	COUNT(P.NMPRODUCT) AS PRODUCTYPE,
	SUM(R.VLTOTAL) AS VLTOTALREQUEST,
	AVG(PR.VLUNITARY) AS AVGREQUEST
FROM REQUEST AS R
INNER JOIN CUSTOMER AS C ON R.CDCUSTOMER = C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST = R.CDREQUEST
INNER JOIN PRODUCT AS P ON P.CDPRODUCT = PR.CDPRODUCT
GROUP BY R.DTREQUEST, C.NMCUSTOMER) AS RESULTADO
ORDER BY RESULTADO.PRODUCTYPE;

--LETRA F
SELECT*
FROM
(SELECT 	
	S.NMSUPPLIER,
	COUNT (P.CDSUPPLIER) AS TLPRODUCT 
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER 
GROUP BY S.NMSUPPLIER,P.CDSUPPLIER) AS FORNECEDOR
WHERE FORNECEDOR.TLPRODUCT>1

--LETRA G
SELECT* FROM
(SELECT DISTINCT
	P.NMPRODUCT,
	COUNT(PR.CDPRODUCT) AS QTVEZES,
	SUM (PR.QTAMOUNT) AS TOTALP
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
GROUP BY NMPRODUCT) AS PRODUCT
WHERE PRODUCT.QTVEZES<2
--APENAS PRA VISUALIZAR
SELECT *FROM PRODUCT
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST

--LETRA H
SELECT *
FROM
(SELECT 
	C.NMCUSTOMER,
	P.NMPRODUCT,
	PR.QTAMOUNT*PR.VLUNITARY AS TOTAL,
	COUNT(PR.CDPRODUCT)AS TOTALP,
	S.NMSUPPLIER
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
INNER JOIN REQUEST AS R ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C ON C.CDCUSTOMER=R.CDCUSTOMER
INNER JOIN SUPPLIER AS S ON S.CDSUPPLIER=P.CDSUPPLIER
ORDER BY  P.NMPRODUCT) AS RESULT
order BY RESULT.NMCUSTOMER
-----
SELECT *
FROM
(SELECT 
	C.NMCUSTOMER,
	P.NMPRODUCT,
	PR.QTAMOUNT*PR.VLUNITARY AS TOTAL,
	COUNT(PR.CDPRODUCT)AS TOTALP,
	S.NMSUPPLIER
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
INNER JOIN REQUEST AS R ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN CUSTOMER AS C ON C.CDCUSTOMER=R.CDCUSTOMER
INNER JOIN SUPPLIER AS S ON S.CDSUPPLIER=P.CDSUPPLIER
GROUP BY C.NMCUSTOMER,P.NMPRODUCT,S.NMSUPPLIER) AS RESULTADO
WHERE RESULTADO.TOTAL>1000
ORDER BY RESULTADO.NMCUSTOMER,RESULTADO.NMPRODUCT


SELECT *FROM PRODUCT
SELECT *FROM SUPPLIER
SELECT *FROM REQUEST
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCTREQUEST

