--DEIXAR AQUI CASO DER RUIM
BEGIN TRANSACTION
--LISTA 6

SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM SUPPLIER 

INSERT INTO SUPPLIER VALUES (13,'NAOTEMPROD.','(011)523-43')
INSERT INTO CUSTOMER VALUES (10,'TESTANDO','3435-2343','DESCONHECIDO')
INSERT INTO CUSTOMER VALUES (9,'ATACADO TEST','3435-2343','DESCONHECIDO')

--1 LETRA A
SELECT *FROM CUSTOMER

DELETE  FROM CUSTOMER 
WHERE CDCUSTOMER NOT IN(
	SELECT CDCUSTOMER FROM REQUEST
);


--LETRA B 
DELETE FROM SUPPLIER
WHERE CDSUPPLIER NOT IN(
	SELECT CDSUPPLIER FROM PRODUCT
);

--LETRA C
UPDATE PRODUCTREQUEST
SET VLUNITARY = P.VLPRICE
FROM PRODUCTREQUEST AS PR
INNER JOIN PRODUCT AS P ON PR.CDPRODUCT = P.CDPRODUCT
WHERE PR.VLUNITARY != P.VLPRICE;
UPDATE REQUEST
SET VLTOTAL = RESULT.TOTAL
FROM (
SELECT
	CDREQUEST,
	SUM(VLUNITARY * QTAMOUNT) AS TOTAL
FROM PRODUCTREQUEST
GROUP BY CDREQUEST
) AS RESULT
WHERE REQUEST.CDREQUEST = RESULT.CDREQUEST

--LETRA D
ALTER TABLE SUPPLIER
ADD ddsstatus VARCHAR(10) NULL;

--LETRA E 
UPDATE SUPPLIER
SET ddsstatus ='INATIVO'
WHERE CDSUPPLIER NOT IN(
	SELECT CDSUPPLIER FROM PRODUCT
);

--LETRA F
UPDATE CUSTOMER 
SET NMADRESS = 'DESCONHECIDO'
WHERE NMADRESS=NULL;

--LETRA G
BEGIN TRAN

DELETE FROM PRODUCTREQUEST
INSERT INTO PRODUCTREQUEST (A.CDREQUEST, CDPRODUCT, QTAMOUNT, VLUNITARY)
SELECT A.CDREQUEST, B.CDPRODUCT, 10, B.VLPRICE FROM REQUEST A, PRODUCT B

ROLLBACK TRAN

ROLLBACK TRAN; 

--2 LETRA A
SELECT 
	C.NMCUSTOMER,
	P.NMPRODUCT,
	COUNT(P.NMPRODUCT) AS VEZESCOMPRADO,
	SUM(R.VLTOTAL) AS TOTALPAGO
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON C.CDCUSTOMER = R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT AS P ON PR.CDPRODUCT = P.CDPRODUCT 
GROUP BY C.NMCUSTOMER, P.NMPRODUCT
ORDER BY C.NMCUSTOMER;

-- LETRA B
SELECT 
	NMCUSTOMER,
	COUNT(R.CDCUSTOMER) AS TOTAL,
	SUM(R.VLTOTAL) AS TOTALCOMPRADO
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON C.CDCUSTOMER = R.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON R.CDREQUEST = PR.CDREQUEST
INNER JOIN PRODUCT D ON PR.CDPRODUCT = D.CDPRODUCT
WHERE YEAR(R.DTREQUEST) = 2003
GROUP BY NMCUSTOMER;

--LETRA C 

SELECT 
	 S.NMSUPPLIER,
	 S.IDFONE,
	 P.NMPRODUCT,
	 P.VLPRICE,
	 P.QTSTOCK
 FROM SUPPLIER AS S
 INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
UNION ALL
SELECT
	NMSUPPLIER, IDFONE,
	NULL,NULL,NULL
FROM SUPPLIER 
WHERE CDSUPPLIER NOT IN (
	SELECT CDSUPPLIER FROM PRODUCT
);

--LETRA D
SELECT 
C.NMCUSTOMER,R.DTREQUEST,R.VLTOTAL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON R.CDCUSTOMER=C.CDCUSTOMER
UNION ALL
SELECT 
C.NMCUSTOMER,NULL,NULL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON R.CDCUSTOMER=C.CDCUSTOMER
WHERE C.CDCUSTOMER NOT IN (
	SELECT C.CDCUSTOMER FROM REQUEST
);

SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM CUSTOMER