--LISTA 7
BEGIN TRAN

SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM SUPPLIER 

--LETRA A

ALTER TABLE PRODUCTREQUEST 
NOCHECK CONSTRAINT FKPRODUCTREQREQUEST----NOCHECK CONSTRAINT UTILIZAR ESSE COMANDO PRA 'IGNORAR' A CHAVE
DELETE FROM REQUEST
WHERE VLTOTAL<1000 AND 
CDREQUEST NOT IN (
	SELECT CDREQUEST FROM PRODUCTREQUEST) AND DTREQUEST BETWEEN '2003/06/01' AND '2003/06/30';

--LETRA B
UPDATE PRODUCT SET PRODUCT.VLPRICE = TABELA.AVGUNITARY
FROM (SELECT CDPRODUCT,
			AVG(VLUNITARY) AS AVGUNITARY,
			SUM(CDPRODUCT) AS AMOUNT
 FROM PRODUCTREQUEST
 GROUP BY CDPRODUCT
) AS TABELA
WHERE PRODUCT.CDPRODUCT = TABELA.CDPRODUCT
AND AMOUNT < 800;

--LETRA C
INSERT INTO CUSTOMER SELECT CDSUPPLIER+9, NMSUPPLIER, IDFONE, 'DESCONHECIDO' FROM SUPPLIER ;
--SO PRA CONFERIR (NAO ESQUECE DE DAR BEGIN TRAN ANTES)
SELECT *FROM CUSTOMER

--LETRA D

SELECT DTREQUEST,DTDELIVER,DIFERENÇA.DIFERENÇA,DIFERENÇA.VLTOTAL FROM
(SELECT DTREQUEST,DTDELIVER, DATEDIFF(DAY,DTREQUEST,DTDELIVER) AS DIFERENÇA, VLTOTAL FROM REQUEST)AS DIFERENÇA
WHERE DIFERENÇA.DIFERENÇA=10 AND  VLTOTAL<10000
UPDATE REQUEST
SET DTDELIVER= DATEADD(DAY,30,DTREQUEST)



ROLLBACK TRAN; 