

BEGIN TRANSACTION;

--LISTA 5
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT
SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM SUPPLIER 

INSERT INTO PRODUCT VALUES (29,'TEST2',11,27.6556,600)
INSERT INTO PRODUCT VALUES (28,'TEST',9,27.6556,500)
INSERT INTO SUPPLIER VALUES (12,'NADA','(011)454-5)')
INSERT INTO PRODUCT VALUES (30,'agua mineral',12,27.6556,500)


--LETRA A
SELECT 
	P.NMPRODUCT,
	COUNT(PR.CDPRODUCT) AS TOTAL
FROM PRODUCT AS P
INNER JOIN PRODUCTREQUEST AS PR ON P.CDPRODUCT = PR.CDPRODUCT
GROUP BY P.NMPRODUCT
UNION ALL 
SELECT 
	NMPRODUCT,
	NULL
FROM PRODUCT 
WHERE CDPRODUCT NOT IN (
	SELECT CDPRODUCT FROM PRODUCTREQUEST
)
GROUP BY NMPRODUCT;

--LETRA B
SELECT
	S.NMSUPPLIER,
	COUNT (P.CDPRODUCT) AS TOTALPRODUCT
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY S.NMSUPPLIER

UNION ALL
 
SELECT
	S.NMSUPPLIER,
	NULL
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE S.CDSUPPLIER NOT IN (
	SELECT CDSUPPLIER FROM PRODUCT
)GROUP BY S.NMSUPPLIER

--TENTATIVA
/*SELECT*FROM
(SELECT 
	S.NMSUPPLIER,
	COUNT (P.CDPRODUCT) AS TOTALPRODUCT
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
GROUP BY S.NMSUPPLIER)AS RES
WHERE RES.TOTALPRODUCT NOT IN(
 SELECT RES.TOTALPRODUCT FROM PRODUCT
 )
SELECT
	S.NMSUPPLIER,
	COUNT (P.CDPRODUCT) AS TOTALPRODUCT
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE =NULL
GROUP BY S.NMSUPPLIER
HAVING COUNT(*)=NULL

SELECT *FROM SUPPLIER 
SELECT *FROM PRODUCT
*/

--LETRA C
SELECT
	S.NMSUPPLIER,
	P.NMPRODUCT,
	SUM (PR.QTAMOUNT) as total
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDPRODUCT=P.CDPRODUCT
GROUP BY S.NMSUPPLIER,P.NMPRODUCT

UNION ALL

SELECT
	S.NMSUPPLIER,'TOTAL',
	
	SUM (PR.QTAMOUNT) as total
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDPRODUCT=P.CDPRODUCT
GROUP BY S.NMSUPPLIER
UNION ALL

SELECT
	'TOTAL','GERAL',
	
	SUM (PR.QTAMOUNT) as total
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDPRODUCT=P.CDPRODUCT
GROUP BY S.NMSUPPLIER




--LETRA D

SELECT
C.NMCUSTOMER,
P.NMPRODUCT,
SUM (PR.QTAMOUNT*PR.VLUNITARY) AS TOTAL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON R.CDCUSTOMER=C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
GROUP BY C.NMCUSTOMER,P.NMPRODUCT

UNION ALL

SELECT
CLIENTE.NMCUSTOMER,
'TOTAL',
SUM(CLIENTE.TOTAL)

FROM
(SELECT
C.NMCUSTOMER,
'TOTAL'as j,
SUM (PR.QTAMOUNT*PR.VLUNITARY) AS TOTAL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON R.CDCUSTOMER=C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
GROUP BY C.NMCUSTOMER,P.NMPRODUCT)AS CLIENTE
GROUP BY CLIENTE.NMCUSTOMER

UNION ALL

SELECT
' ','TOTAL GERAL',SUM(TOTALGERAL.TOTAL)
FROM
(SELECT
CLIENTE.NMCUSTOMER,
'TOTAL'AS J,
SUM(CLIENTE.TOTAL) AS TOTAL

FROM
(SELECT
C.NMCUSTOMER,
'TOTAL'as j,
SUM (PR.QTAMOUNT*PR.VLUNITARY) AS TOTAL
FROM CUSTOMER AS C
INNER JOIN REQUEST AS R ON R.CDCUSTOMER=C.CDCUSTOMER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDREQUEST=R.CDREQUEST
INNER JOIN PRODUCT AS P ON P.CDPRODUCT=PR.CDPRODUCT
GROUP BY C.NMCUSTOMER,P.NMPRODUCT)AS CLIENTE
GROUP BY CLIENTE.NMCUSTOMER) AS TOTALGERAL


--LETRA E 
SELECT 
NMCUSTOMER, 
IDFONE
FROM CUSTOMER 
WHERE CDCUSTOMER NOT IN(
	SELECT CDCUSTOMER FROM REQUEST
	);



--LETRA F
--adicionei o produto no fornecedor 'nada'
SELECT 
S.NMSUPPLIER, 
S.IDFONE
FROM SUPPLIER AS S
INNER JOIN PRODUCT AS P ON P.CDSUPPLIER=S.CDSUPPLIER
WHERE P.NMPRODUCT LIKE '%leite em po%' OR P.NMPRODUCT LIKE '%agua mineral%';

SELECT *FROM PRODUCTREQUEST
SELECT *FROM REQUEST
SELECT *FROM CUSTOMER
SELECT *FROM PRODUCT

--LETRA G

SELECT
TOTAL.NMPRODUCT,
TOTAL.NMSUPPLIER,
TOTAL.TOTAL
FROM
(SELECT 
P.NMPRODUCT,
S.NMSUPPLIER, 
COUNT (PR.CDREQUEST) AS TOTAL
FROM PRODUCT AS P
INNER JOIN SUPPLIER AS S ON P.CDSUPPLIER=S.CDSUPPLIER
INNER JOIN PRODUCTREQUEST AS PR ON PR.CDPRODUCT=P.CDPRODUCT
GROUP BY S.NMSUPPLIER,P.NMPRODUCT) AS TOTAL
WHERE TOTAL.TOTAL>3

ROLLBACK;